name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
      - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      T: ${{ secrets.T }}
      X: ${{ secrets.X }}
      U: ${{ secrets.U }}
      Z: ${{ secrets.Z }}
      B: ${{ secrets.B }}
      N: ${{ secrets.N }}
      M: ${{ secrets.M }}
      Q: ${{ secrets.Q }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: node index.js
